"""Stable initial event names."""

from enum import Enum


class EventType(str, Enum):
    SYSTEM_STARTED = "system.started"
    SYSTEM_READY = "system.ready"
    SYSTEM_STOPPING = "system.stopping"
    SYSTEM_ERROR = "system.error"
    VOICE_LISTENING = "voice.listening"
    VOICE_TRANSCRIPTION = "voice.transcription"
    VOICE_COMMAND = "voice.command"
    BRAIN_STARTED = "brain.started"
    BRAIN_COMPLETED = "brain.completed"
    BRAIN_FAILED = "brain.failed"
    SKILL_STARTED = "skill.started"
    SKILL_COMPLETED = "skill.completed"
    SKILL_FAILED = "skill.failed"
    PLANNER_STARTED = "planner.started"
    PLANNER_COMPLETED = "planner.completed"
    PLANNER_FAILED = "planner.failed"
    TTS_STARTED = "tts.started"
    TTS_COMPLETED = "tts.completed"
    TTS_STOPPED = "tts.stopped"
    TTS_FAILED = "tts.failed"
    MEMORY_CREATED = "memory.created"
    MEMORY_REMOVED = "memory.removed"
    MEMORY_RECALLED = "memory.recalled"
    CONTEXT_UPDATED = "context.updated"
    VISION_CAPTURE_STARTED = "vision.capture_started"
    VISION_CAPTURE_COMPLETED = "vision.capture_completed"
    VISION_CAPTURE_FAILED = "vision.capture_failed"
    UI_MESSAGE = "ui.message"
    SECURITY_ALLOWED = "security.allowed"
    SECURITY_CONFIRMATION_REQUIRED = "security.confirmation_required"
    SECURITY_DENIED = "security.denied"
    SECURITY_CONFIRMED = "security.confirmed"
    SECURITY_EXPIRED = "security.expired"
    DIAGNOSTICS_STATUS_CHANGED = "diagnostics.status_changed"
    MCP_SERVER_CONNECTED = "mcp.server_connected"
    MCP_SERVER_DISCONNECTED = "mcp.server_disconnected"
    MCP_TOOL_STARTED = "mcp.tool_started"
    MCP_TOOL_COMPLETED = "mcp.tool_completed"
    MCP_TOOL_FAILED = "mcp.tool_failed"
    RUNTIME_STARTED = "runtime.started"
    SERVICE_STARTING = "service.starting"
    SERVICE_ONLINE = "service.online"
    SERVICE_ERROR = "service.error"
    SERVICE_RESTARTING = "service.restarting"
    SERVICE_STOPPED = "service.stopped"
    RUNTIME_STOPPING = "runtime.stopping"
    RUNTIME_STOPPED = "runtime.stopped"
